# Generated by Django 2.0.2 on 2018-02-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=120)),
                ('konten', models.TextField(max_length=1200)),
            ],
        ),
    ]
